version: 1.0.{build}
image: Visual Studio 2017

before_build:
- cmd: nuget restore

build:
  project: XboxWebApi.sln
  verbosity: minimal

for:
-
  branches:
    only:
      - master
  
  build:
    publish_nuget: true

  nuget:
    account_feed: true
    project_feed: true
  
  deploy:
    provider: NuGet
    api_key:
      secure: E0p43N+15qo1Ma9B9/06PMM5xDYJvQYfb5ffbfv3M058/wsQlQrNumu2DOzp/pwI
    skip_symbols: false
    
- 
  branches: 
    except: 
      - master
